server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:lb://AUTH-SERVICE}
              predicates:
                - Path=/auth/**

            - id: order-service
              uri: ${ORDER_SERVICE_URL:lb://ORDER-SERVICE}
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@userKeyResolver}"
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1

            - id: inventory-service
              uri: ${INVENTORY_SERVICE_URL:lb://INVENTORY-SERVICE}
              predicates:
                - Path=/api/v1/inventory/**

            - id: pricing-service
              uri: ${PRICING_SERVICE_URL:lb://PRICING-SERVICE}
              predicates:
                - Path=/api/pricing/**

            - id: delivery-service
              uri: ${DELIVERY_SERVICE_URL:lb://DELIVERY-SERVICE}
              predicates:
                - Path=/api/v1/deliveries/**

            - id: websocket-service
              uri: ${WEBSOCKET_SERVICE_URL:lb://WEBSOCKET-SERVICE}
              predicates:
                - Path=/ws/**

jwt:
  secret: ${JWT_SECRET}