server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: ${ORDER_SERVICE_URL:lb://ORDER-SERVICE}
              predicates:
                - Path=/api/v1/orders/**

            - id: inventory-service
              uri: ${INVENTORY_SERVICE_URL:lb://INVENTORY-SERVICE}
              predicates:
                - Path=/api/v1/inventory/**

            - id: payment-service
              uri: ${PAYMENT_SERVICE_URL:lb://PAYMENT-SERVICE}
              predicates:
                - Path=/api/payments/**

            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URL:lb://NOTIFICATION-SERVICE}
              predicates:
                - Path=/api/notifications/**

            - id: delivery-service
              uri: ${DELIVERY_SERVICE_URL:lb://DELIVERY-SERVICE}
              predicates:
                - Path=/api/v1/deliveries/**

            - id: saga-orchestrator
              uri: ${SAGA_ORCHESTRATOR_URL:lb://SAGA-ORCHESTRATOR}
              predicates:
                - Path=/api/orchestrator/**

jwt:
  secret: ${JWT_SECRET:MyVerySecretKeyForJwtAuthentication123456789}