server:
  port: 8089

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    ttl: 10m

    ttl-jitter: 60s

    missing-ttl: 30s
    lock:
      ttl: 5s
      retry-delay: 50ms
      max-retries: 20

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
